### Numpy Library

In [1]:
#Q1: What is Numpy? 

#A1: Numpy is a powerful numerical computing library in Python that provides support for arrays, matrices, and many mathematical
#    functions to operate on them.

In [2]:
#Q2: How do you create a Numpy array?

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


In [3]:
#Q3: How do you create an array of zeros or ones?

zeros_arr = np.zeros(5)
ones_arr = np.ones(5)
print(zeros_arr)
print(ones_arr)


[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [4]:
#Q4: How do you perform element-wise addition, subtraction, multiplication, and division with Numpy arrays?

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [5]:
#Q5: How do you find the mean, median, and standard deviation of an array? 

data = np.array([1, 2, 3, 4, 5])
print(np.mean(data))
print(np.median(data))
print(np.std(data))


3.0
3.0
1.4142135623730951


In [6]:
#Q6: How do you reshape a Numpy array? 

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape((2, 3))
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


In [7]:
#Q7: How do you create an array with a range of values?

arr = np.arange(0, 10, 2)
print(arr)


[0 2 4 6 8]


In [8]:
#Q8: How do you find the maximum and minimum values in an array?

arr = np.array([1, 2, 3, 4, 5])
print(np.max(arr))
print(np.min(arr))


5
1


In [9]:
#Q9: How do you transpose a Numpy array?

arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = arr.transpose()
print(transposed_arr)


In [10]:
#Q10: How do you concatenate two arrays? 

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print(concatenated_arr)


[1 2 3 4 5 6]


In [11]:
#Q11: How do you create a 2D array (matrix)?

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
#Q12: How do you flatten a 2D array to a 1D array?

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
flattened = matrix.flatten()
print(flattened)


[1 2 3 4 5 6 7 8 9]


In [13]:
#Q13: How do you generate random numbers with Numpy?

random_arr = np.random.random((3, 3))
print(random_arr)


[[0.25170728 0.08028988 0.64896042]
 [0.52376919 0.28343437 0.4355923 ]
 [0.98617817 0.82984725 0.49247886]]


In [14]:
#Q14: How do you save and load a Numpy array to/from a file?

arr = np.array([1, 2, 3, 4, 5])
np.save('my_array.npy', arr)
loaded_arr = np.load('my_array.npy')
print(loaded_arr)


[1 2 3 4 5]


In [15]:
#Q15: How do you find the unique elements in an array?

arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_arr = np.unique(arr)
print(unique_arr)


[1 2 3 4 5]


In [16]:
#Q16: How do you perform matrix multiplication?

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
# or
result = matrix1 @ matrix2
print(result)


[[19 22]
 [43 50]]


In [17]:
#Q17: How do you get the shape of an array? 

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)


(2, 3)


In [18]:
#Q18: How do you index and slice a Numpy array?

arr = np.array([1, 2, 3, 4, 5])
print(arr[2])  # Output: 3
print(arr[1:4])  # Output: [2 3 4]


3
[2 3 4]


In [19]:
#Q19: How do you generate an array of evenly spaced values?

arr = np.linspace(0, 1, 5)
print(arr)


[0.   0.25 0.5  0.75 1.  ]


In [20]:
#Q20: How do you find the sum, mean, and standard deviation along a specific axis?

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sum_along_axis0 = np.sum(matrix, axis=0)  # Sum along the columns
sum_along_axis1 = np.sum(matrix, axis=1)  # Sum along the rows
mean_along_axis0 = np.mean(matrix, axis=0)
std_along_axis0 = np.std(matrix, axis=0)

print("Sum along columns:", sum_along_axis0)
print("Sum along rows:", sum_along_axis1)
print("Mean along columns:", mean_along_axis0)
print("Standard deviation along columns:", std_along_axis0)


Sum along columns: [12 15 18]
Sum along rows: [ 6 15 24]
Mean along columns: [4. 5. 6.]
Standard deviation along columns: [2.44948974 2.44948974 2.44948974]
